spring:
  application:
    name: read-through-cache
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/read-through-cache
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  post: 9000